In [3]:
import numpy as np
import matplotlib.pyplot as py
import pandas as pd
%matplotlib inline
from sklearn.linear_model import LinearRegression

Consider the following five training examples

			X=[2,3,4,5,6]
            Y=[12.8978,17.7586,23.3192,28.3129,32.1351]
We want to learn a function f(x) of the form f(x)=ax+bwhich is parameterized by (a, b).Using squared error as the loss function,  which parameters would you use to model this function

In [2]:
X=[2,3,4,5,6]
Y=[12.8978,17.7586,23.3192,28.3129,32.1351]

In [9]:
dict={'X':X,'Y':Y}

In [14]:
df_x=pd.DataFrame(X)
df_y=pd.DataFrame(Y)

In [17]:
lreg=LinearRegression()

In [18]:
lreg.fit(df_x,df_y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [19]:
lreg.coef_

array([[4.90289]])

In [20]:
lreg.intercept_

array([3.27316])

A study was conducted to understand the effect of number of hours the students spent studying to their performance in the final exams. You are given the following 8 samples from the study.

What is the best linear fit on this dataset?
* Hours spent studying = [10, 9, 2, 15, 10, 16, 11, 16]
* Marks scored in final exam = [95, 80, 10, 50, 85, 98, 38, 93]


	

In [23]:
hours=[10,9,2,15,10,16,11,16]
marks=[95,80,10,50,85,98,38,93]

In [25]:
data_x=pd.DataFrame(hours)
data_y=pd.DataFrame(marks)

In [32]:
dlreg=LinearRegression(normalize=True)

In [33]:
dlreg.fit(data_x,data_y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=True)

In [34]:
dlreg.coef_

array([[4.29354047]])

In [35]:
dlreg.intercept_

array([20.85936222])