synthetic dataset: https://bit.ly/2yXJJDA

The dataset contains 1000 points and each input point contains 3 features.

In [2]:
#importing pandas 

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
#reading the dataset

train_x=pd.read_csv("LR_X.csv")
train_y=pd.read_csv("LR_Y.csv")

In [4]:
#dimensions of the dataset

print(train_x.shape)
print(train_y.shape)

(999, 3)
(999, 1)


In [5]:
train_x.head()

0.26  0.08  0.28
0  0.26  0.52  0.01
1  0.85  0.60  0.14
2  0.94  0.22  0.48
3  0.53  0.05  0.76
4  0.07  0.59  0.63

# Performing Linear Regression

Q)Train a linear regression model (without regularization) on the above dataset. Report the coefficients of the best fit model. Report the coefficients in the 
	   following format:β0,β1,β2,β3

In [6]:
from sklearn.linear_model import LinearRegression

In [7]:
lreg=LinearRegression()

In [8]:
lreg.fit(train_x,train_y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [13]:
#Values of β1,β2,β3
lreg.coef_

array([[-1.2,  2.1,  2.2]])

In [14]:
#Value of β0
lreg.intercept_

array([1.])

# Regularization using Ridge Regression 

Q)Train a l2 regularized linear regression model on the above dataset. Vary theregularization parameter from 1 to 10. As you increase the regularization 
	   parameter, absolute value of the coefficients (excluding the intercept) of the model:

In [10]:
from sklearn.linear_model import Ridge

In [15]:
#changing the alpha parameter to observe the change in the absolute values of coefficients 
clf = Ridge(alpha=10)
clf.fit(train_x, train_y)

Ridge(alpha=10, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=0.001)

In [16]:
clf.coef_


array([[-1.06164378,  1.86331294,  1.95859155]])

* The value of the coefficient decreases as the alpha value is increased from 1 to 10